[package]
name = "rgssad"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
tokio = { version = "1", optional = true }

[dev-dependencies]
tokio = { version = "1", features = [ "rt", "macros" ] }

[features]
# Enable tokio wrappers
tokio = ["dep:tokio"]
